name: appifylab_assessment
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  another_flushbar: ^1.12.30
  flutter_screenutil: ^5.9.3
  pull_to_refresh_flutter3: ^2.0.2
  flutter_reaction_button: ^3.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
flutter:
  uses-material-design: true
  assets:
    - assets/